/* automatically generated by rust-bindgen */

pub const BUF_SIZE_MAP_NS: ::std::os::raw::c_uint = 256;
#[repr(C)]
pub struct bpf_map_def {
    pub type_: ::std::os::raw::c_uint,
    pub key_size: ::std::os::raw::c_uint,
    pub value_size: ::std::os::raw::c_uint,
    pub max_entries: ::std::os::raw::c_uint,
    pub map_flags: ::std::os::raw::c_uint,
    pub pinning: ::std::os::raw::c_uint,
    pub namespace: [::std::os::raw::c_char; 256usize],
}
#[test]
fn bindgen_test_layout_bpf_map_def() {
    assert_eq!(::std::mem::size_of::<bpf_map_def>() , 280usize , concat ! (
               "Size of: " , stringify ! ( bpf_map_def ) ));
    assert_eq! (::std::mem::align_of::<bpf_map_def>() , 4usize , concat ! (
                "Alignment of " , stringify ! ( bpf_map_def ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const bpf_map_def ) ) . type_ as * const _ as
                usize } , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( bpf_map_def ) , "::" ,
                stringify ! ( type_ ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const bpf_map_def ) ) . key_size as * const _
                as usize } , 4usize , concat ! (
                "Alignment of field: " , stringify ! ( bpf_map_def ) , "::" ,
                stringify ! ( key_size ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const bpf_map_def ) ) . value_size as * const _
                as usize } , 8usize , concat ! (
                "Alignment of field: " , stringify ! ( bpf_map_def ) , "::" ,
                stringify ! ( value_size ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const bpf_map_def ) ) . max_entries as * const
                _ as usize } , 12usize , concat ! (
                "Alignment of field: " , stringify ! ( bpf_map_def ) , "::" ,
                stringify ! ( max_entries ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const bpf_map_def ) ) . map_flags as * const _
                as usize } , 16usize , concat ! (
                "Alignment of field: " , stringify ! ( bpf_map_def ) , "::" ,
                stringify ! ( map_flags ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const bpf_map_def ) ) . pinning as * const _ as
                usize } , 20usize , concat ! (
                "Alignment of field: " , stringify ! ( bpf_map_def ) , "::" ,
                stringify ! ( pinning ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const bpf_map_def ) ) . namespace as * const _
                as usize } , 24usize , concat ! (
                "Alignment of field: " , stringify ! ( bpf_map_def ) , "::" ,
                stringify ! ( namespace ) ));
}
#[repr(C)]
pub struct bpf_map {
    pub fd: ::std::os::raw::c_int,
    pub def: bpf_map_def,
}
#[test]
fn bindgen_test_layout_bpf_map() {
    assert_eq!(::std::mem::size_of::<bpf_map>() , 284usize , concat ! (
               "Size of: " , stringify ! ( bpf_map ) ));
    assert_eq! (::std::mem::align_of::<bpf_map>() , 4usize , concat ! (
                "Alignment of " , stringify ! ( bpf_map ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const bpf_map ) ) . fd as * const _ as usize }
                , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( bpf_map ) , "::" ,
                stringify ! ( fd ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const bpf_map ) ) . def as * const _ as usize }
                , 4usize , concat ! (
                "Alignment of field: " , stringify ! ( bpf_map ) , "::" ,
                stringify ! ( def ) ));
}
extern "C" {
    #[link_name = "_Z20bpf_apply_relocation"]
    pub fn bpf_apply_relocation(fd: ::std::os::raw::c_int,
                                insn: *mut bpf_insn);
}
extern "C" {
    #[link_name = "_Z14bpf_create_map"]
    pub fn bpf_create_map(map_type: bpf_map_type,
                          key_size: ::std::os::raw::c_int,
                          value_size: ::std::os::raw::c_int,
                          max_entries: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "_Z12bpf_load_map"]
    pub fn bpf_load_map(map_def: *mut bpf_map_def,
                        path: *const ::std::os::raw::c_char) -> *mut bpf_map;
}
extern "C" {
    #[link_name = "_Z13bpf_prog_load"]
    pub fn bpf_prog_load(prog_type: bpf_prog_type, insns: *const bpf_insn,
                         prog_len: ::std::os::raw::c_int,
                         license: *const ::std::os::raw::c_char,
                         kern_version: ::std::os::raw::c_int,
                         log_buf: *mut ::std::os::raw::c_char,
                         log_size: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "_Z18bpf_update_element"]
    pub fn bpf_update_element(fd: ::std::os::raw::c_int,
                              key: *mut ::std::os::raw::c_void,
                              value: *mut ::std::os::raw::c_void,
                              flags: ::std::os::raw::c_ulonglong)
     -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "_Z19perf_event_open_map"]
    pub fn perf_event_open_map(pid: ::std::os::raw::c_int,
                               cpu: ::std::os::raw::c_int,
                               group_fd: ::std::os::raw::c_int,
                               flags: ::std::os::raw::c_ulong)
     -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy)]
pub struct bpf_insn {
    pub _address: u8,
}
impl Clone for bpf_insn {
    fn clone(&self) -> Self { *self }
}
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum bpf_map_type { }
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum bpf_prog_type { }
#[repr(C)]
#[derive(Debug, Copy)]
pub struct bpf_insn {
    pub _address: u8,
}
impl Clone for bpf_insn {
    fn clone(&self) -> Self { *self }
}
